# Generated by Django 6.0.3 on 2026-03-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='data',
            new_name='postado_em',
        ),
    ]
