# Generated by Django 6.0.3 on 2026-03-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_rename_data_postagem_postado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='postado_em',
            new_name='publicado_em',
        ),
    ]
