# Generated by Django 6.0.3 on 2026-03-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0003_rename_postado_em_postagem_publicado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='publicado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
