# Generated by Django 6.0.5 on 2026-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0007_postagem_cor_fundo_postagem_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='cor_fundo',
            new_name='gradiente_fundo',
        ),
        migrations.AlterField(
            model_name='postagem',
            name='gradiente_fundo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
