# Generated by Django 6.0.3 on 2026-03-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='matricula',
            new_name='username',
        ),
    ]
