# Generated by Django 6.0.3 on 2026-03-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='data',
            new_name='publicado_em',
        ),
    ]
