# Generated by Django 6.0.3 on 2026-03-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_rename_data_noticia_publicado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='publicado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
