"""empty message

Revision ID: 0970af9f59c6
Revises: 579bb4a50dcb
Create Date: 2026-08-20 22:36:16.293606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0970af9f59c6'
down_revision = '579bb4a50dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=False),
    sa.Column('corpo', sa.String(length=324), nullable=False),
    sa.Column('imagem', sa.String(length=512), nullable=True),
    sa.Column('gradiente', sa.String(length=64), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postagem')
    # ### end Alembic commands ###
