"""empty message

Revision ID: 183e6c41bfb3
Revises: afab585e3228
Create Date: 2026-09-02 10:12:40.770867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183e6c41bfb3'
down_revision = 'afab585e3228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setor', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('setor')

    # ### end Alembic commands ###
