"""empty message

Revision ID: 3287fed11702
Revises: a36c71084d85
Create Date: 2026-08-22 17:29:11.862235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3287fed11702'
down_revision = 'a36c71084d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.drop_column('publicado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicado_em', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
