"""empty message

Revision ID: 579bb4a50dcb
Revises: ee0a68c46398
Create Date: 2026-08-20 21:51:07.552131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '579bb4a50dcb'
down_revision = 'ee0a68c46398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
