"""empty message

Revision ID: a36c71084d85
Revises: a7d9708c003e
Create Date: 2026-08-22 16:16:12.747558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36c71084d85'
down_revision = 'a7d9708c003e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('imagem', sa.String(length=512), nullable=True),
    sa.Column('fonte', sa.Enum('G1', 'METROPOLES', 'UOL', 'CNN', name='fonte'), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('visibilidade', sa.Enum('RASCUNHO', 'PUBLICADA', name='visibilidade'), nullable=False),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticia')
    # ### end Alembic commands ###
