"""empty message

Revision ID: a7d9708c003e
Revises: 0970af9f59c6
Create Date: 2026-08-22 10:31:43.987384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d9708c003e'
down_revision = '0970af9f59c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Enum('NEGADA', 'REVISAO', 'APROVADA', name='estado'), nullable=False))
        batch_op.add_column(sa.Column('visibilidade', sa.Enum('RASCUNHO', 'PUBLICADA', name='visibilidade'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagem', schema=None) as batch_op:
        batch_op.drop_column('visibilidade')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
