"""empty message

Revision ID: ee0a68c46398
Revises: 412fad05f546
Create Date: 2026-08-20 18:59:11.624192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0a68c46398'
down_revision = '412fad05f546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricula', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['matricula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('matricula')

    # ### end Alembic commands ###
