"""empty message

Revision ID: f98133e4beb5
Revises: 3287fed11702
Create Date: 2026-08-23 12:36:54.184516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f98133e4beb5'
down_revision = '3287fed11702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.alter_column('corpo',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.alter_column('corpo',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
